# Generated by Django 4.0 on 2024-01-15 14:20

from django.db import migrations
from django.db.migrations import RunPython


def create_statuses(apps, schema_editor):
    Status = apps.get_model('models_app', 'Status')
    Status.objects.get_or_create(state='На модерации')
    Status.objects.get_or_create(state='На удалении')
    Status.objects.get_or_create(state='На отклонении')
    Status.objects.get_or_create(state='Одобрена')
    Status.objects.get_or_create(state='Отклонен')


class Migration(migrations.Migration):
    dependencies = [
        ('models_app', '0001_initial'),
    ]

    operations = [
        RunPython(create_statuses)
    ]
