# Generated by Django 4.0 on 2024-01-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0003_alter_comment_answer_post_posts_updated_21e495_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(upload_to='pictures/image/%Y/%m/%d', verbose_name='Картинка'),
        ),
    ]
