# Generated by Django 4.0 on 2024-01-22 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0004_alter_picture_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_user', to='models_app.user', verbose_name='Пользователь'),
        ),
    ]
